# Generated by Django 4.2.4 on 2023-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.svg', null=True, upload_to='avatars/'),
        ),
    ]
